version: '3'

services:
  ui:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:lts-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/opt/ui
    working_dir: /opt/ui

  server:
    image: server
    build: 
      context: .
      dockerfile: server/src/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    ports:
      - "5240:5240"
  